[toolchain]
channel = "1.75.0"
components = [
    "rustc",
    "cargo", 
    "rustfmt",
    "clippy",
    "rust-src",
    "rust-analysis",
    "rls",
    "rust-analyzer"
]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-gnu",
    "bpf-unknown-unknown"
]
profile = "default"

[env]
# Rust flags for better performance and security
RUSTFLAGS = "-C target-cpu=native -D warnings"
# Cargo flags for better build performance
CARGO_INCREMENTAL = "1"
CARGO_TARGET_DIR = "target"
# Memory settings for large builds
CARGO_BUILD_JOBS = "4"
