[features]
seeds = false
skip-lint = false

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[programs.devnet]
finova_core = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
finova_token = "2"
finova_nft = "3"
finova_defi = "4"
finova_bridge = "5"
finova_oracle = "6"

[workspace]
members = [
    "programs/finova-core",
    "programs/finova-token",
    "programs/finova-nft",
    "programs/finova-defi",
    "programs/finova-bridge",
    "programs/finova-oracle"
]

[test]
startup_wait = 10000
