# Podfile for FinovaExample
#
# This file specifies the dependencies for the Finova Network Super App.
# To install, run `pod install` in the terminal from the `Example` directory.

platform :ios, '15.0'

target 'FinovaExample' do
  # This flag is required for using Swift in CocoaPods.
  use_frameworks!

  # Core Finova SDK (replace with the actual pod when available)
  # pod 'FinovaSDK', '~> 1.0'

  # Networking
  # pod 'Alamofire', '~> 5.8'

  # UI & Charts
  # pod 'Charts', '~> 5.0' # For advanced analytics dashboards
  # pod 'SwiftCharts', :git => 'https://github.com/danielgindi/Charts.git'

  # Web3 & Crypto
  # pod 'Solana.Swift', :git => 'https://github.com/metaplex-foundation/Solana.Swift.git'
  # pod 'WalletConnectSwiftV2', '~> 1.0'

  # Add other necessary pods for production:
  # - Analytics (Firebase, Segment)
  # - Crash Reporting (Sentry, Crashlytics)
  # - Image Caching (Kingfisher, SDWebImage)

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
