[toolchain]

[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
finova_core = "FinovaCoreProgram11111111111111111111111111"
finova_token = "FinovaTokenProgram111111111111111111111111"
finova_nft = "FinovaNftProgram1111111111111111111111111"
finova_defi = "FinovaDefiProgram1111111111111111111111111"
finova_oracle = "FinovaOracleProgram111111111111111111111111"
finova_bridge = "FinovaBridgeProgram111111111111111111111111"

[programs.devnet]
finova_core = "FinovaCoreProgram11111111111111111111111111"
finova_token = "FinovaTokenProgram111111111111111111111111"
finova_nft = "FinovaNftProgram1111111111111111111111111"
finova_defi = "FinovaDefiProgram1111111111111111111111111"
finova_oracle = "FinovaOracleProgram111111111111111111111111"
finova_bridge = "FinovaBridgeProgram111111111111111111111111"

[programs.testnet]
finova_core = "FinovaCoreProgram11111111111111111111111111"
finova_token = "FinovaTokenProgram111111111111111111111111"
finova_nft = "FinovaNftProgram1111111111111111111111111"
finova_defi = "FinovaDefiProgram1111111111111111111111111"
finova_oracle = "FinovaOracleProgram111111111111111111111111"
finova_bridge = "FinovaBridgeProgram111111111111111111111111"

[programs.mainnet]
finova_core = "FinovaCoreProgram11111111111111111111111111"
finova_token = "FinovaTokenProgram111111111111111111111111"
finova_nft = "FinovaNftProgram1111111111111111111111111"
finova_defi = "FinovaDefiProgram1111111111111111111111111"
finova_oracle = "FinovaOracleProgram111111111111111111111111"
finova_bridge = "FinovaBridgeProgram111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/finova-core",
    "programs/finova-token", 
    "programs/finova-nft",
    "programs/finova-defi",
    "programs/finova-oracle",
    "programs/finova-bridge"
]

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "metadata.so"

[[test.genesis]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
program = "spl_token.so"

[[test.genesis]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
program = "spl_token_2022.so"

[[test.genesis]]
address = "ASSoKZrJ1WA93w7n2qcg6K8GQsevs7aKDn5sHrn3PwG"
program = "spl_associated_token_account.so"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[[test.validator.clone]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"

[[test.validator.clone]]
address = "ASSoKZrJ1WA93w7n2qcg6K8GQsevs7aKDn5sHrn3PwG"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgrade_authority_off = false
skip_deploy = false

[build]
docker = false
